# Generated by Django 4.2.7 on 2023-11-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
    ]
