# Generated by Django 4.2.7 on 2023-11-16 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_alter_useraccount_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='new_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Please enter a phone number with correct format.', regex='09(0[0-3]|1[0-9]|3[1-9]|2[1-9])-?[0-9]{3}-?[0-9]{4}')], verbose_name='New Unverified Phone Number'),
        ),
    ]
