# Generated by Django 4.2.7 on 2023-12-06 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0006_alter_useraccountprofilepicture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountprofilepicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='User Account Profile Picture'),
        ),
    ]
