# Generated by Django 4.2.7 on 2025-02-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPTypeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_type', models.CharField(choices=[('timer_counter_based', 'Both Timer and Counter Based'), ('counter_based', 'Counter Based'), ('timer_based', 'Timer Based')], max_length=19, verbose_name='OTP Type')),
                ('max_attempt_count', models.IntegerField(default=3, verbose_name='Max Possible Attempt Number (For "Counter Based" and "Both Timer and Counter Based" OTPs)')),
                ('expire_after', models.IntegerField(default=180, verbose_name='Expire OTP After (Seconds) [For "Timer Based" and "Both Timer and Counter Based" OTPs]')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'OTP Type and Setting',
                'verbose_name_plural': 'OTP Types and Settings',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=200, verbose_name='One Time Password Code')),
                ('otp_usage', models.CharField(choices=[('activate_account', 'Account Activation OTP'), ('verify_login', 'Login Verification OTP'), ('reset_password', 'Password Reset OTP'), ('update_account', 'Account Update Verification OTP'), ('delete_account', 'Account Delete Verification OTP'), ('general_verification', 'General Verification (For Shopping, etc...)')], max_length=20, verbose_name='OTP Usage')),
                ('otp_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='OTP Code Creation Date')),
                ('attempt_counter', models.PositiveIntegerField(default=0, verbose_name='Number of Attempts')),
                ('last_attempt', models.DateTimeField(auto_now=True, verbose_name='Last Attempt')),
                ('otp_type_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otp.otptypesetting', verbose_name='OTP Type and Setting')),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
            },
        ),
    ]
