# Generated by Django 4.2.7 on 2023-11-13 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_type', models.CharField(choices=[('timer_counter_based', 'Both Timer and Counter Based'), ('counter_based', 'Counter Based')], max_length=19, verbose_name='OTP Type')),
                ('otp_usage', models.CharField(choices=[('account_verification', 'Account Verification'), ('new_phone_number_verification', 'New Phone Number Verification'), ('reset_password', 'Forgotten Password'), ('OTP_login', 'ONE Time Password Login')], max_length=29, verbose_name='OTP Usage')),
                ('otp_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Currrent OTP Code Creation Date')),
                ('expire_after', models.PositiveIntegerField(blank=True, null=True, verbose_name='Expiration Date')),
                ('try_counter', models.PositiveIntegerField(default=0, verbose_name='Number of Attempts')),
                ('last_try', models.DateTimeField(auto_now=True, verbose_name='Last Attempt')),
                ('need_recreation', models.BooleanField(default=False, verbose_name='Does User Need New OTP Code?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OTPCode', to=settings.AUTH_USER_MODEL, verbose_name='Related User')),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
            },
        ),
    ]
