# Generated by Django 4.2.7 on 2023-11-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='max_possible_try',
            field=models.PositiveIntegerField(default=3, verbose_name='Maximum possible number of Attempts'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(default=123456, max_length=20, verbose_name='OTP Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp_type',
            field=models.CharField(choices=[('timer_counter_based', 'Both Timer and Counter Based'), ('counter_based', 'Counter Based'), ('timer_based', 'Timer Based')], max_length=19, verbose_name='OTP Type'),
        ),
    ]
