# Generated by Django 4.2.7 on 2023-11-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_alter_otpcode_max_possible_try_alter_otpcode_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_after',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Expire After (Seconds)'),
        ),
    ]
