# Generated by Django 4.2.7 on 2023-11-18 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0004_alter_otpcode_expire_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_after',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30)], verbose_name='Expire After (Seconds)'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='max_possible_try',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3)], verbose_name='Maximum possible number of Attempts'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(max_length=20, verbose_name='One Time Password Code'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp_usage',
            field=models.CharField(max_length=50, verbose_name='OTP Usage'),
        ),
    ]
