# Generated by Django 4.2.7 on 2024-02-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_alter_otpcode_expire_after_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='need_recreation',
        ),
    ]
