# Generated by Django 4.2.7 on 2024-02-01 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0006_remove_otpcode_need_recreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='max_possible_try',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum possible number of Attempts'),
        ),
    ]
